default:
  dora_dir: /home/user/dev/audiocraft_${oc.env:USER}
  partitions:
    global: debug
    team: debug
  reference_dir: /home/user/dev
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: /home/user/dev/audiocraft_${oc.env:USER}
  partitions:
    global: debug
    team: debug
  reference_dir: /home/user/dev
