# @package __global__

datasource:
  max_sample_rate: 32000
  max_channels: 1

  train: /content/drive/MyDrive/musicgen_dataset
  valid: /content/drive/MyDrive/musicgen_dataset
  evaluate: /content/drive/MyDrive/musicgen_dataset
  generate: /content/drive/MyDrive/musicgen_dataset # identical to evaluate
