# @package __global__

datasource:
  max_sample_rate: 32000
  max_channels: 1

  train: egs/music/songsinger_5k_32khz/train
  valid: egs/music/songsinger_5k_32khz/valid
  evaluate: egs/music/songsinger_5k_32khz/test
  generate: egs/music/songsinger_5k_32khz/test # identical to evaluate
