# @package __global__

datasource:
  max_sample_rate: 32000
  max_channels: 1

  train: egs/music/songsinger_5k_32khz
  valid: egs/music/songsinger_5k_32khz
  evaluate: egs/music/songsinger_5k_32khz
  generate: egs/music/songsinger_5k_32khz # identical to evaluate
